name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to shared hosting
      uses: easingthemes/ssh-deploy@v2.4.13
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        server: yourserver.com
        username: yourusername
        remote_path: /path/to/your/app
        local_path: .next/
